#! /usr/bin/env python3
# -*- coding: utf-8 -*-

'''
      Copyright 2017, 王思远 <darknightghost.cn@gmail.com>
      This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
      You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
'''

import os
import sys
import Formater
import time

def main(argv):
    #Aanalyse arguments
    if "-h" in argv or "--help" in argv or "-?" in argv:
        usage(argv[0])
        return 0

    elif len(argv) < 3:
        usage(argv[0])
        return -1

    device_path = argv[-1]
    formater_name = argv[1]
    args = argv[1 : -1]

    #Open device
    try:
        f = os.open(device_path,os.O_RDONLY)

    except Exception as e:
        print(str(e))
        return -1

    #Open formater
    try:
        formater = Formater.open_recv_formater(formater_name, args)

    except FileNotFoundError:
        print("Fomater does not exists.")
        os.close(f)
        return -1

    do_recv(f, formater);
    print("")
    return 0

def usage(name):
    print("Usage:\n"
            "\t%s formater [formater-arguments] device")
    return

def do_recv(dev_fd, formater):
    try:
        while True:
            data = os.read(dev_fd, 4096)
            if len(data) > 0:
                print("%d byte(s) received."%len(data))
                formater.on_data(data)

            else:
                time.sleep(1)

    except KeyboardInterrupt:
        pass


ret = main(sys.argv)
exit(ret)
